name: gym
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  font_awesome_flutter: ^10.12.0
  icons_plus: ^5.0.0
  flutter_svg: ^2.2.2

  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0
  provider: ^6.1.5+1
  firebase_storage: ^13.0.4
  flutter_image_compress: ^2.4.0
  path_provider: ^2.1.5
  image_picker: ^1.2.1
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  firebase_messaging: ^16.0.4
  flutter_gen: ^5.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: FjallaOne
      fonts:
        - asset: assets/fonts/FjallaOne-Regular.ttf
