// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import "package:firebase_core/firebase_core.dart" show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-fcj3ugK87dwtPxwS3eyWY_jHrny4SNY',
    appId: '1:967139721516:web:af467b01447107adbe2c89',
    messagingSenderId: '967139721516',
    projectId: 'gymweb-1e348',
    authDomain: 'gymweb-1e348.firebaseapp.com',
    storageBucket: 'gymweb-1e348.firebasestorage.app',
    measurementId: 'G-E8T8MHG9HN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoPEkHmHBy269nm-CCclCuhdErqUGXxRY',
    appId: '1:967139721516:android:d390ecd04053cd97be2c89',
    messagingSenderId: '967139721516',
    projectId: 'gymweb-1e348',
    storageBucket: 'gymweb-1e348.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA947eDXNP95nFsSr3bBb0uG7ezVkTQz0g',
    appId: '1:967139721516:ios:d16c4e8284c92c7fbe2c89',
    messagingSenderId: '967139721516',
    projectId: 'gymweb-1e348',
    storageBucket: 'gymweb-1e348.firebasestorage.app',
    iosBundleId: 'com.example.gym',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA947eDXNP95nFsSr3bBb0uG7ezVkTQz0g',
    appId: '1:967139721516:ios:d16c4e8284c92c7fbe2c89',
    messagingSenderId: '967139721516',
    projectId: 'gymweb-1e348',
    storageBucket: 'gymweb-1e348.firebasestorage.app',
    iosBundleId: 'com.example.gym',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-fcj3ugK87dwtPxwS3eyWY_jHrny4SNY',
    appId: '1:967139721516:web:f7bccb80b347877fbe2c89',
    messagingSenderId: '967139721516',
    projectId: 'gymweb-1e348',
    authDomain: 'gymweb-1e348.firebaseapp.com',
    storageBucket: 'gymweb-1e348.firebasestorage.app',
    measurementId: 'G-7YX6304JDK',
  );

}